
name: Test Notebook

on:
  push:
    branches:
      - main

jobs:
  test-notebook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install jupyter nbconvert papermill

      - name: Execute Notebook
        run: papermill i200658_i202478_Mlops_A1.ipynb i200658_i202478_Mlops_A1_output.ipynb

      - name: Parse Notebook Output
        run: |
          # Add script to parse notebook output and check for test results
          # Mark the job as failed if tests fail
